<?php

declare(strict_types=1);

namespace CraftCms\Commerce\Purchasable\Elements;

use craft\commerce\Plugin;
use CraftCms\Cms\Element\Contracts\NestedElementInterface;
use CraftCms\Cms\Element\Element;
use CraftCms\Cms\Support\Facades\I18N;
use CraftCms\Cms\Support\Facades\Sites;
use CraftCms\Cms\Support\Html;
use CraftCms\Cms\Support\Money as MoneyHelper;
use CraftCms\Commerce\Catalog\Models\CatalogPricingRule;
use CraftCms\Commerce\CatalogPricing\CatalogPricing;
use CraftCms\Commerce\CatalogPricing\CatalogPricingRules;
use CraftCms\Commerce\Database\Table;
use CraftCms\Commerce\Helpers\Cp as CommerceCp;
use CraftCms\Commerce\Helpers\Currency;
use CraftCms\Commerce\Helpers\Localization;
use CraftCms\Commerce\Helpers\Purchasable as PurchasableHelper;
use CraftCms\Commerce\Inventory\Inventory;
use CraftCms\Commerce\Inventory\Models\InventoryItem;
use CraftCms\Commerce\Inventory\Models\InventoryLevel;
use CraftCms\Commerce\Inventory\Records\InventoryItem as InventoryItemRecord;
use CraftCms\Commerce\Order\Elements\Order;
use CraftCms\Commerce\Order\LineItem\Data\LineItem;
use CraftCms\Commerce\Order\LineItem\Enums\LineItemType;
use CraftCms\Commerce\Order\Models\OrderNotice;
use CraftCms\Commerce\Payment\Currencies;
use CraftCms\Commerce\Promotion\Models\Sale;
use CraftCms\Commerce\Promotion\Sales;
use CraftCms\Commerce\Purchasable\Contracts\PurchasableInterface;
use CraftCms\Commerce\Purchasable\Purchasables;
use CraftCms\Commerce\Purchasable\Records\Purchasable as PurchasableRecord;
use CraftCms\Commerce\Purchasable\Records\PurchasableStore;
use CraftCms\Commerce\Purchasable\Validation\PurchasableRules;
use CraftCms\Commerce\Shipping\Models\ShippingCategory;
use CraftCms\Commerce\Shipping\ShippingCategories;
use CraftCms\Commerce\Store\Contracts\HasStoreInterface;
use CraftCms\Commerce\Store\Models\Store;
use CraftCms\Commerce\Store\Stores;
use CraftCms\Commerce\Tax\Models\TaxCategory;
use CraftCms\Commerce\Tax\TaxCategories;
use CraftCms\RulesetValidation\Attributes\Ruleset;
use Illuminate\Support\Collection;
use Money\Money;
use Money\Teller;
use yii\validators\Validator;
use function CraftCms\Cms\t;

#[Ruleset(PurchasableRules::class)]
abstract class Purchasable extends Element implements PurchasableInterface, HasStoreInterface
{
    private ?float $_salePrice = null;

    private ?float $_price = null;

    /**
     * @var Sale[]|null
     */
    private ?array $_sales = null;

    /**
     * Promotional price generated by the sales system.
     */
    private ?float $_salesPrice = null;

    /**
     * The store based on the `siteId` of the instance of the purchasable.
     */
    private ?Store $_store = null;

    private ?float $_promotionalPrice = null;

    private string $_sku = '';

    private ?int $_taxCategoryId = null;

    private ?TaxCategory $_taxCategory = null;

    private ?int $_shippingCategoryId = null;

    private ?ShippingCategory $_shippingCategory = null;

    public ?float $width = null;

    public ?float $height = null;

    public ?float $length = null;

    public ?float $weight = null;

    private ?float $_basePrice = null;

    private ?float $_basePromotionalPrice = null;

    /**
     * The ID of the catalog pricing rule that is affecting the sale price of this purchasable.
     */
    public ?int $catalogPricingRuleId = null;

    private ?CatalogPricingRule $_catalogPricingRule = null;

    public bool $freeShipping = false;

    public bool $promotable = false;

    public bool $availableForPurchase = true;

    public ?int $minQty = null;

    public ?int $maxQty = null;

    public ?int $inventoryItemId = null;

    /**
     * This is if the store cares about tracking the stock.
     */
    public bool $inventoryTracked = false;

    /**
     * Should this purchases of this purchasable be allowed if it is out of stock.
     */
    public bool $allowOutOfStockPurchases = false;

    /**
     * This is the cached total available stock across all inventory locations.
     */
    private ?int $_stock = null;

    public function attributes(): array
    {
        $names = parent::attributes();

        $names[] = 'isAvailable';
        $names[] = 'isPromotable';
        $names[] = 'price';
        $names[] = 'promotionalPrice';
        $names[] = 'basePrice';
        $names[] = 'basePromotionalPrice';
        $names[] = 'onPromotion';
        $names[] = 'salePrice';
        $names[] = 'sku';
        $names[] = 'stock';
        $names[] = 'inventoryTracked';
        $names[] = 'allowOutOfStockPurchases';
        $names[] = 'shippingCategoryId';
        $names[] = 'taxCategoryId';

        return $names;
    }

    public function fields(): array
    {
        $fields = parent::fields();

        $fields['salePrice'] = 'salePrice';

        foreach ($this->currencyAttributes() as $attribute) {
            $fields[$attribute . 'AsCurrency'] = $attribute . 'AsCurrency';
        }

        return $fields;
    }

    public function extraFields(): array
    {
        $names = parent::extraFields();

        $names[] = 'description';
        $names[] = 'sales';
        $names[] = 'snapshot';
        return $names;
    }

    public function currencyAttributes(): array
    {
        return [
            'basePrice',
            'basePromotionalPrice',
            'price',
            'promotionalPrice',
            'salePrice',
        ];
    }

    public function getBasePriceAsCurrency(): string
    {
        return $this->_currencyAttributeAsCurrency('basePrice');
    }

    public function getBasePromotionalPriceAsCurrency(): string
    {
        return $this->_currencyAttributeAsCurrency('basePromotionalPrice');
    }

    public function getPriceAsCurrency(): string
    {
        return $this->_currencyAttributeAsCurrency('price');
    }

    public function getPromotionalPriceAsCurrency(): string
    {
        return $this->_currencyAttributeAsCurrency('promotionalPrice');
    }

    public function getSalePriceAsCurrency(): string
    {
        return $this->_currencyAttributeAsCurrency('salePrice');
    }

    private function _currencyAttributeAsCurrency(string $attribute): string
    {
        $amount = $this->$attribute ?? 0;
        return Currency::formatAsCurrency($amount, $this->getStore()->getCurrency());
    }

    public function setAttributesFromRequest(array $values): void
    {
        $length = $values['length'] ?? null;
        unset($values['length']);
        if ($length !== null) {
            $this->length = $length ? (float)Localization::normalizeNumber($length) : null;
        }

        $width = $values['width'] ?? null;
        unset($values['width']);
        if ($width !== null) {
            $this->width = $width ? (float)Localization::normalizeNumber($width) : null;
        }

        $height = $values['height'] ?? null;
        unset($values['height']);
        if ($height !== null) {
            $this->height = $height ? (float)Localization::normalizeNumber($height) : null;
        }

        $weight = $values['weight'] ?? null;
        unset($values['weight']);
        if ($weight !== null) {
            $this->weight = $weight ? (float)Localization::normalizeNumber($weight) : null;
        }

        $this->setAttributes($values);
    }

    protected function inlineAttributeInputHtml(string $attribute): string
    {
        $localizePrice = function(string $attribute) {
            $price = $this->{$attribute};
            if (empty($this->getErrors($attribute))) {
                if ($price === null && $attribute === 'basePromotionalPrice') {
                    return null;
                } elseif ($price === null) {
                    $price = 0;
                }

                $price = I18N::getFormatter()->asDecimal($price);
            }

            return $price;
        };

        return match ($attribute) {
            'availableForPurchase' => PurchasableHelper::availableForPurchaseInputHtml($this->availableForPurchase),
            'price' => Currency::moneyInputHtml($localizePrice('basePrice'), [
                'id' => 'base-price',
                'name' => 'basePrice',
                'currency' => $this->getStore()->getCurrency()->getCode(),
                'currencyLabel' => $this->getStore()->getCurrency()->getCode(),
            ]),
            'promotionalPrice' => Currency::moneyInputHtml($localizePrice('basePromotionalPrice'), [
                'id' => 'base-promotional-price',
                'name' => 'basePromotionalPrice',
                'currency' => $this->getStore()->getCurrency()->getCode(),
                'currencyLabel' => $this->getStore()->getCurrency()->getCode(),
            ]),
            'sku' => PurchasableHelper::skuInputHtml($this->getSkuAsText()),
            default => parent::inlineAttributeInputHtml($attribute),
        };
    }

    public static function displayName(): string
    {
        $classNameParts = explode('\\', static::class);

        return array_pop($classNameParts);
    }

    private function getTeller(): Teller
    {
        return app(Currencies::class)->getTeller($this->getStore()->getCurrency());
    }

    public function __unset(string $name): void
    {
        // Allow clearing of specific memoized properties
        if (in_array($name, ['stock', 'shippingCategory', 'taxCategory'])) {
            $this->{'_' . $name} = null;
            return;
        }

        parent::__unset($name);
    }

    public function getStore(): Store
    {
        if ($this->_store === null || !in_array($this->siteId, $this->_store->getSites()->pluck('id')->all())) {
            if ($this->siteId === null) {
                throw new \RuntimeException('Purchasable::siteId cannot be null');
            }

            $this->_store = app(Stores::class)->getStoreBySiteId($this->siteId);
            if ($this->_store === null) {
                throw new \RuntimeException('Unable to retrieve store.');
            }
        }

        return $this->_store;
    }

    public function getStoreId(): int
    {
        return $this->getStore()->id;
    }

    public function getIsAvailable(): bool
    {
        // Is the element available for purchase?
        if (!$this->availableForPurchase) {
            return false;
        }

        // is the element enabled?
        if ($this->getStatus() !== self::STATUS_ENABLED) {
            return false;
        }

        // Temporary SKU can not be added to the cart
        if (PurchasableHelper::isTempSku($this->getSku())) {
            return false;
        }

        if (static::hasInventory() && $this->inventoryTracked && $this->getStock() < 1) {
            if (!app(Purchasables::class)->isPurchasableOutOfStockPurchasingAllowed($this)) {
                return false;
            }
        }

        return true;
    }

    public function setBasePrice(Money|array|float|int|null $basePrice): void
    {
        if (is_array($basePrice)) {
            if (isset($basePrice['value']) && $basePrice['value'] === '') {
                $this->_basePrice = null;
                return;
            }

            if (!isset($basePrice['currency'])) {
                $basePrice['currency'] = $this->getStore()->getCurrency();
            }

            $basePrice = MoneyHelper::toMoney($basePrice);
            // nullify if conversion fails
            $basePrice = $basePrice ?: null;
        }

        if ($basePrice instanceof Money) {
            $basePrice = MoneyHelper::toDecimal($basePrice);
        } elseif ($basePrice !== null) {
            $basePrice = (float)$basePrice;
        }

        $this->_basePrice = $basePrice;
    }

    public function getBasePrice(): ?float
    {
        return $this->_basePrice;
    }

    public function setBasePromotionalPrice(Money|array|float|int|null $basePromotionalPrice): void
    {
        if (is_array($basePromotionalPrice)) {
            if (isset($basePromotionalPrice['value']) && $basePromotionalPrice['value'] === '') {
                $this->_basePromotionalPrice = null;
                return;
            }

            if (!isset($basePromotionalPrice['currency'])) {
                $basePromotionalPrice['currency'] = $this->getStore()->getCurrency();
            }

            $basePromotionalPrice = MoneyHelper::toMoney($basePromotionalPrice);
            // nullify if conversion fails
            $basePromotionalPrice = $basePromotionalPrice ?: null;
        }

        if ($basePromotionalPrice instanceof Money) {
            $basePromotionalPrice = MoneyHelper::toDecimal($basePromotionalPrice);
        } elseif ($basePromotionalPrice !== null) {
            $basePromotionalPrice = (float)$basePromotionalPrice;
        }

        $this->_basePromotionalPrice = $basePromotionalPrice;
    }

    public function getBasePromotionalPrice(): ?float
    {
        return $this->_basePromotionalPrice;
    }

    public function setPrice(?float $price): void
    {
        $this->_price = $price;
    }

    public function getPrice(): ?float
    {
        if (!app(CatalogPricingRules::class)->canUseCatalogPricingRules()) {
            return $this->basePrice;
        }

        $price = $this->_price ?? $this->basePrice;

        return (float)$this->getTeller()->convertToString($price);
    }

    public function getPromotionalPrice(): ?float
    {
        $price = $this->getPrice();
        if (!app(CatalogPricingRules::class)->canUseCatalogPricingRules()) {
            // Use the sales system to figure out the price
            if (!isset($this->_sales)) {
                $this->loadSales();
            }
            $promotionalPrice = $this->_salesPrice ?? $this->basePromotionalPrice;
        } else {
            $promotionalPrice = $this->_promotionalPrice ?? $this->basePromotionalPrice;
        }

        if ($promotionalPrice === null) {
            return null;
        }

        $promotionalPrice = (float)$this->getTeller()->convertToString($promotionalPrice);
        return $this->getTeller()->lessThan($promotionalPrice, $price) ? $promotionalPrice : null;
    }

    public function setPromotionalPrice(?float $price): void
    {
        $this->_promotionalPrice = $price;
    }

    public function getCatalogPricingRule(): ?CatalogPricingRule
    {
        if ($this->_catalogPricingRule === null && $this->catalogPricingRuleId !== null) {
            $this->_catalogPricingRule = app(CatalogPricingRules::class)->getCatalogPricingRuleById($this->catalogPricingRuleId, $this->storeId);
        }

        return $this->_catalogPricingRule;
    }

    public function getSalePrice(): ?float
    {
        if ($this->_salePrice === null) {
            $this->_salePrice = $this->getPromotionalPrice() ?? $this->getPrice();
        }

        return $this->_salePrice ?? null;
    }

    public function getSku(): string
    {
        return $this->_sku ?? '';
    }

    /**
     * Returns the SKU as text but returns a blank string if it's a temp SKU.
     */
    public function getSkuAsText(): string
    {
        $sku = $this->getSku();

        if (PurchasableHelper::isTempSku($sku)) {
            $sku = '';
        }

        return $sku;
    }

    public function setSku(?string $sku = null): void
    {
        $this->_sku = $sku;
    }

    /**
     * Returns whether this variant has stock.
     */
    public function hasStock(): bool
    {
        return !$this->inventoryTracked || $this->getStock() > 0;
    }

    public function setTaxCategoryId(?int $taxCategoryId = null): void
    {
        $this->_taxCategoryId = $taxCategoryId;
    }

    public function getTaxCategoryId(): int
    {
        if ($this->_taxCategoryId === null) {
            $this->_taxCategoryId = app(TaxCategories::class)->getDefaultTaxCategory()->id;
        }

        return $this->_taxCategoryId;
    }

    public function getTaxCategory(): TaxCategory
    {
        if ($this->_taxCategory === null || $this->_taxCategory->id != $this->getTaxCategoryId()) {
            $this->_taxCategory = app(TaxCategories::class)->getTaxCategoryById($this->getTaxCategoryId());
        }

        return $this->_taxCategory;
    }

    public function getSnapshot(): array
    {
        return [
            'catalogPricingRuleId' => $this->catalogPricingRuleId,
        ];
    }

    public function setShippingCategoryId(?int $shippingCategoryId = null): void
    {
        $this->_shippingCategoryId = $shippingCategoryId;
    }

    public function getShippingCategoryId(): int
    {
        if ($this->_shippingCategoryId === null) {
            $this->_shippingCategoryId = app(ShippingCategories::class)->getDefaultShippingCategory($this->getStoreId())->id;
        }

        return $this->_shippingCategoryId;
    }

    public function getShippingCategory(): ShippingCategory
    {
        if ($this->_shippingCategory === null || $this->_shippingCategory->id !== $this->getShippingCategoryId()) {
            $this->_shippingCategory = app(ShippingCategories::class)->getShippingCategoryById($this->getShippingCategoryId(), $this->getStoreId());
        }

        return $this->_shippingCategory;
    }

    public function getDescription(): string
    {
        return (string)$this;
    }

    public function populateLineItem(LineItem $lineItem): void
    {
        // Since we do not have a proper stock reservation system, we need deduct stock if they have more in the cart than is available, and to do this quietly.
        // If this occurs in the payment request, the user will be notified the order has changed.
        if (($order = $lineItem->getOrder()) && !$order->isCompleted) {
            if ($this::hasInventory() &&
                !$this->getIsOutOfStockPurchasingAllowed() &&
                $this->inventoryTracked &&
                ($lineItem->qty > $this->getStock()) &&
                $this->getStock() > 0
            ) {
                $message = t('{description} only has {stock} in stock.', ['description' => $lineItem->getDescription(), 'stock' => $this->getStock()], category: 'commerce');
                $notice = new OrderNotice([
                    'type' => 'lineItemMaxStockReached',
                    'attribute' => "lineItems.$lineItem->id.qty",
                    'message' => $message,
                ]);
                $order->addNotice($notice);
                $lineItem->qty = $this->getStock();
            }
        }

        $lineItem->weight = (float)$this->weight; //converting nulls
        $lineItem->height = (float)$this->height; //converting nulls
        $lineItem->length = (float)$this->length; //converting nulls
        $lineItem->width = (float)$this->width; //converting nulls
    }

    public function getLineItemRules(LineItem $lineItem): array
    {
        $order = $lineItem->getOrder();

        // After the order is complete shouldn't check things like stock being available or the purchasable being around since they are irrelevant.
        if ($order && $order->isCompleted) {
            return [];
        }

        $lineItemQuantitiesByPurchasableId = [];
        foreach ($order->getLineItems() as $item) {
            if ($item->purchasableId) {
                $lineItemQuantitiesByPurchasableId[$item->purchasableId] = isset($lineItemQuantitiesByPurchasableId[$item->purchasableId]) ? $lineItemQuantitiesByPurchasableId[$item->purchasableId] + $item->qty : $item->qty;
            }
        }

        return [
            // an inline validator defined as an anonymous function
            [
                'purchasableId',
                function($attribute, $params, Validator $validator) use ($lineItem) {
                    $purchasable = $lineItem->getPurchasable();
                    if ($purchasable === null) {
                        $validator->addError($lineItem, $attribute, t('No purchasable available.', category: 'commerce'));
                    }

                    if (!app(Purchasables::class)->isPurchasableAvailable($lineItem->getPurchasable(), $lineItem->getOrder())) {
                        $validator->addError($lineItem, $attribute, t('The item is not enabled for sale.', category: 'commerce'));
                    }
                },
            ],
            [
                'qty',
                function($attribute, $params, Validator $validator) use ($lineItem, $lineItemQuantitiesByPurchasableId) {
                    if ($lineItem->type == LineItemType::Custom) {
                        return;
                    }

                    $lineItemPurchasable = $lineItem->getPurchasable();
                    if (!$lineItemPurchasable instanceof Purchasable) {
                        return;
                    }

                    if (!$this->hasStock()) {
                        if (!app(Purchasables::class)->isPurchasableOutOfStockPurchasingAllowed($lineItemPurchasable, $lineItem->getOrder())) {
                            $error = t('"{description}" is currently out of stock.', ['description' => $lineItemPurchasable->getDescription()], category: 'commerce');
                            $validator->addError($lineItem, $attribute, $error);
                        }
                    }

                    $lineItemQty = $lineItem->purchasableId ? $lineItemQuantitiesByPurchasableId[$lineItem->purchasableId] : $lineItem->qty;

                    if ($this->hasStock() && $this->inventoryTracked && $lineItemQty > $this->getStock()) {
                        if (!app(Purchasables::class)->isPurchasableOutOfStockPurchasingAllowed($lineItemPurchasable, $lineItem->getOrder())) {
                            $error = t('There are only {num} "{description}" items left in stock.', ['num' => $this->getStock(), 'description' => $lineItemPurchasable->getDescription()], category: 'commerce');
                            $validator->addError($lineItem, $attribute, $error);
                        }
                    }

                    if ($this->minQty > 1 && $lineItemQty < $this->minQty) {
                        $error = t('Minimum order quantity for this item is {num}.', ['num' => $this->minQty], category: 'commerce');
                        $validator->addError($lineItem, $attribute, $error);
                    }

                    if ($this->maxQty != 0 && $lineItemQty > $this->maxQty) {
                        $error = t('Maximum order quantity for this item is {num}.', ['num' => $this->maxQty], category: 'commerce');
                        $validator->addError($lineItem, $attribute, $error);
                    }
                },
            ],
        ];
    }

    public function setAttributes($values): void
    {
        // Normalize category IDs - handle arrays from componentSelect and empty strings
        if (isset($values['taxCategoryId'])) {
            if (is_array($values['taxCategoryId'])) {
                $values['taxCategoryId'] = reset($values['taxCategoryId']) ?: null;
            }
            if ($values['taxCategoryId'] === '') {
                $values['taxCategoryId'] = null;
            }
        }
        if (isset($values['shippingCategoryId'])) {
            if (is_array($values['shippingCategoryId'])) {
                $values['shippingCategoryId'] = reset($values['shippingCategoryId']) ?: null;
            }
            if ($values['shippingCategoryId'] === '') {
                $values['shippingCategoryId'] = null;
            }
        }

        parent::setAttributes($values);
    }

    public function afterOrderComplete(Order $order, LineItem $lineItem): void
    {
    }

    public function hasFreeShipping(): bool
    {
        return $this->freeShipping;
    }

    public function getIsShippable(): bool
    {
        return true;
    }

    public function getIsTaxable(): bool
    {
        return true;
    }

    public function getIsPromotable(): bool
    {
        return $this->promotable;
    }

    public function getPromotionRelationSource(): mixed
    {
        return $this->id;
    }

    public function getInventoryItem(): InventoryItem
    {
        return app(Inventory::class)->getInventoryItemByPurchasable($this);
    }

    #[\Deprecated(message: 'in 5.0.0 use [[Purchasable::$inventoryTracked]] instead.')]
    public function getHasUnlimitedStock(): bool
    {
        return !$this::hasInventory() || !$this->inventoryTracked;
    }

    #[\Deprecated(message: 'in 5.0.0 use [[Purchasable::$inventoryTracked]] instead.')]
    public function setHasUnlimitedStock($value): bool
    {
        return $this->inventoryTracked = !$value;
    }

    private function getStockFromLevels(): int
    {
        if (!$this->inventoryTracked) {
            return 0;
        }

        $saleableAmount = 0;
        foreach ($this->getInventoryLevels() as $inventoryLevel) {
            if ($inventoryLevel->availableTotal > 0) {
                $saleableAmount += $inventoryLevel->availableTotal;
            }
        }

        return $saleableAmount;
    }

    public function getIsOutOfStockPurchasingAllowed(): bool
    {
        return app(Purchasables::class)->isPurchasableOutOfStockPurchasingAllowed($this);
    }

    /**
     * Returns the cached total available stock across all inventory locations for this store.
     */
    public function getStock(): int
    {
        if ($this->_stock === null) {
            $this->_stock = $this->getStockFromLevels();
        }

        return $this->_stock;
    }

    /**
     * Returns the total stock across all locations this purchasable is tracked in.
     *
     * @return Collection<int, InventoryLevel>
     */
    public function getInventoryLevels(): Collection
    {
        if (!$this->inventoryTracked) {
            return collect();
        }

        return app(Inventory::class)->getInventoryLevelsForPurchasable($this);
    }

    /**
     * Update purchasable table.
     */
    public function afterSave(bool $isNew): void
    {
        $canonicalPurchasableId = $this->getCanonicalId();
        $purchasableId = $this->id;

        if (!$this->propagating) {
            $isOwnerDraftApplying = false;
            $isOwnerRevisionApplying = false;

            // If this is a nested element, check if the owner is a draft and is being applied
            if ($this instanceof NestedElementInterface) {
                $owner = $this->getOwner();
                // A draft is only being "applied" if the owner is the canonical of the draft.
                // Without this id check, "Save as a new product" from a draft would trip this branch
                // and steal the original variant's inventory item via the transfer logic below.
                $isOwnerDraftApplying = $owner
                    && $owner->getIsCanonical()
                    && $owner->duplicateOf !== null
                    && $owner->duplicateOf->getIsDraft()
                    && $owner->duplicateOf->getCanonicalId() === $owner->id;

                $isOwnerRevisionApplying = $owner
                    && $owner->duplicateOf !== null
                    && $owner->duplicateOf->getIsRevision()
                    && $owner->duplicateOf->getCanonicalId() === $owner->id;
            }

            if (!$this->getIsRevision()) {
                // Reset the purchasable's SKU when it is explicitly being duplicating
                if ($this->duplicateOf !== null && !$isOwnerDraftApplying && !$isOwnerRevisionApplying) {
                    $this->sku = PurchasableHelper::tempSku();
                    // Nullify inventory item so a new one is created
                    $this->inventoryItemId = null;
                }
            }

            $purchasable = PurchasableRecord::find($purchasableId);

            if (!$purchasable) {
                $purchasable = new PurchasableRecord();
            }
            $purchasable->sku = $this->getSku();
            $purchasable->id = $purchasableId;
            $purchasable->width = $this->width;
            $purchasable->height = $this->height;
            $purchasable->length = $this->length;
            $purchasable->weight = $this->weight;
            $purchasable->taxCategoryId = $this->taxCategoryId;

            // Only update the description for the primary site until we have a concept
            // of an order having a site ID
            if ($this->siteId == Sites::getPrimarySite()->id) {
                $purchasable->description = $this->getDescription();
            }

            $purchasable->save();

            // Always create the inventory item even if it's a temporary draft (in the slide) since we want to allow stock to be
            // added to inventory before it is saved as a permanent variant.
            if (static::hasInventory() && $canonicalPurchasableId) {
                /** @var InventoryItemRecord|null $inventoryItem */
                $inventoryItem = null;

                // When applying a draft to its canonical, hand the source's inventory
                // item over so any stock movements made on the draft persist.
                if ($isOwnerDraftApplying && $this->duplicateOf !== null) {
                    $inventoryItem = InventoryItemRecord::where('purchasableId', $this->duplicateOf->id)->first();
                    if ($inventoryItem && $inventoryItem->purchasableId != $canonicalPurchasableId) {
                        $inventoryItem->purchasableId = $canonicalPurchasableId;
                        if (!$inventoryItem->save()) {
                            // Could not transfer (e.g. canonical already has its own row); fall through to the find-or-create below.
                            $inventoryItem = null;
                        }
                    }
                }

                if (!$inventoryItem) {
                    $inventoryItem = app(Inventory::class)->ensureInventoryItemRecord($this);
                }

                if ($inventoryItem) {
                    $this->inventoryItemId = $inventoryItem->id;
                }
            }
        }

        if ($purchasableId) {
            // Set Purchasables stores data
            $purchasableStoreRecord = PurchasableStore::where('purchasableId', $purchasableId)
                ->where('storeId', $this->getStoreId())
                ->first();
            if (!$purchasableStoreRecord) {
                $purchasableStoreRecord = new PurchasableStore();
                $purchasableStoreRecord->storeId = $this->getStore()->id;

                if ($this->propagating) {
                    $purchasableStoreRecord->basePrice = 0;
                    $purchasableStoreRecord->basePromotionalPrice = null;
                    $purchasableStoreRecord->stock = app(Inventory::class)->getInventoryLevelsForPurchasable($this)->sum('availableTotal');
                    $purchasableStoreRecord->inventoryTracked = false;
                    $purchasableStoreRecord->allowOutOfStockPurchases = false;
                    $purchasableStoreRecord->minQty = null;
                    $purchasableStoreRecord->maxQty = null;
                    $purchasableStoreRecord->promotable = false;
                    $purchasableStoreRecord->availableForPurchase = false;
                    $purchasableStoreRecord->freeShipping = false;
                    $purchasableStoreRecord->purchasableId = $purchasableId;
                    $purchasableStoreRecord->shippingCategoryId = app(ShippingCategories::class)->getDefaultShippingCategory($this->getStore()->id)->id;

                    if ($this->duplicateOf !== null) {
                        // If this is a duplicate, copy the values from the original purchasable stores record
                        $purchasableStoreRecordDuplicate = PurchasableStore::where('purchasableId', $this->duplicateOf->id)
                            ->where('storeId', $this->getStoreId())
                            ->first();

                        if ($purchasableStoreRecordDuplicate) {
                            $purchasableStoreRecord->basePrice = $purchasableStoreRecordDuplicate->basePrice;
                            $purchasableStoreRecord->basePromotionalPrice = $purchasableStoreRecordDuplicate->basePromotionalPrice;
                            $purchasableStoreRecord->stock = app(Inventory::class)->getInventoryLevelsForPurchasable($this)->sum('availableTotal');
                            $purchasableStoreRecord->inventoryTracked = $purchasableStoreRecordDuplicate->inventoryTracked;
                            $purchasableStoreRecord->allowOutOfStockPurchases = $purchasableStoreRecordDuplicate->allowOutOfStockPurchases;
                            $purchasableStoreRecord->minQty = $purchasableStoreRecordDuplicate->minQty;
                            $purchasableStoreRecord->maxQty = $purchasableStoreRecordDuplicate->maxQty;
                            $purchasableStoreRecord->promotable = $purchasableStoreRecordDuplicate->promotable;
                            $purchasableStoreRecord->availableForPurchase = $purchasableStoreRecordDuplicate->availableForPurchase;
                            $purchasableStoreRecord->freeShipping = $purchasableStoreRecordDuplicate->freeShipping;
                            $purchasableStoreRecord->shippingCategoryId = $purchasableStoreRecordDuplicate->shippingCategoryId;
                        }
                    }
                }
            }

            if (!$this->propagating) {
                $purchasableStoreRecord->basePrice = $this->basePrice;
                $purchasableStoreRecord->basePromotionalPrice = $this->basePromotionalPrice;
                $purchasableStoreRecord->stock = app(Inventory::class)->getInventoryLevelsForPurchasable($this)->sum('availableTotal');
                $purchasableStoreRecord->inventoryTracked = $this::hasInventory() ? $this->inventoryTracked : false;
                $purchasableStoreRecord->allowOutOfStockPurchases = $this->allowOutOfStockPurchases;
                $purchasableStoreRecord->minQty = $this->minQty;
                $purchasableStoreRecord->maxQty = $this->maxQty;
                $purchasableStoreRecord->promotable = $this->promotable;
                $purchasableStoreRecord->availableForPurchase = $this->availableForPurchase;
                $purchasableStoreRecord->freeShipping = $this->freeShipping;
                $purchasableStoreRecord->purchasableId = $purchasableId;
                $purchasableStoreRecord->shippingCategoryId = $this->getShippingCategoryId();
            }

            $purchasableStoreRecord->save();
        }

        parent::afterSave($isNew);
    }

    public function afterPropagate(bool $isNew): void
    {
        parent::afterPropagate($isNew);

        if (!$this->getIsDraft() && !$this->getIsRevision()) {
            app(CatalogPricing::class)->createCatalogPricingJob([
                'purchasableIds' => [$this->getCanonicalId()],
                'storeId' => $this->getStoreId(),
            ]);
        }
    }

    /**
     * Clean up purchasable table.
     */
    public function afterDelete(): void
    {
        $purchasable = PurchasableRecord::find($this->id);

        $purchasable?->delete();

        parent::afterDelete();
    }

    /**
     * @return Sale[]
     */
    public function getSales(): array
    {
        if (!isset($this->_sales)) {
            $this->loadSales();
        }

        return $this->_sales;
    }

    /**
     * @return Sale[] The sales that relate directly to this purchasable
     */
    public function relatedSales(): array
    {
        return app(Sales::class)->getSalesRelatedToPurchasable($this);
    }

    public function getOnPromotion(): bool
    {
        return $this->getPromotionalPrice() !== null;
    }

    #[\Deprecated(message: 'Use [[getOnPromotion()]] instead.')]
    public function getOnSale(): bool
    {
        \CraftCms\Cms\Support\Facades\Deprecator::log(__METHOD__, 'Purchasable `getOnSale()` method has been deprecated. Use `getOnPromotion()` instead.');
        return $this->getOnPromotion();
    }

    public function attributeLabels(): array
    {
        $labels = parent::attributeLabels();

        return array_merge($labels, ['sku' => 'SKU']);
    }

    protected function metaFieldsHtml(bool $static): string
    {
        $html = parent::metaFieldsHtml($static);

        $html .= $this->taxCategoryFieldHtml($static);

        $html .= $this->shippingCategoryFieldHtml($static);

        return $html;
    }

    /**
     * @return ShippingCategory[]
     */
    protected function availableShippingCategories(): array
    {
        return app(ShippingCategories::class)->getAllShippingCategories($this->storeId)->all();
    }

    protected function shippingCategoryFieldHtml(bool $static): string
    {
        $availableShippingCategories = $this->availableShippingCategories();
        $shippingCategory = collect($availableShippingCategories)->firstWhere('id', $this->shippingCategoryId)
            ?? collect($availableShippingCategories)->first();

        return CommerceCp::shippingCategoryFieldHtml([
            'label' => t('Shipping Category', category: 'commerce'),
            'id' => 'shippingCategoryId',
            'name' => 'shippingCategoryId',
            'value' => $shippingCategory,
            'options' => $availableShippingCategories,
            'limit' => 1,
            'min' => 1,
            'disabled' => $static,
            'create' => false,
            'storeId' => $this->storeId,
        ]);
    }

    /**
     * @return TaxCategory[]
     */
    protected function availableTaxCategories(): array
    {
        return app(TaxCategories::class)->getAllTaxCategories();
    }

    protected function taxCategoryFieldHtml(bool $static): string
    {
        $availableTaxCategories = $this->availableTaxCategories();
        $taxCategory = collect($availableTaxCategories)->firstWhere('id', $this->taxCategoryId)
            ?? collect($availableTaxCategories)->first();

        return CommerceCp::taxCategoryFieldHtml([
            'label' => t('Tax Category', category: 'commerce'),
            'id' => 'taxCategoryId',
            'name' => 'taxCategoryId',
            'value' => $taxCategory,
            'options' => $availableTaxCategories,
            'limit' => 1,
            'min' => 1,
            'disabled' => $static,
            'create' => false,
        ]);
    }

    protected function attributeHtml(string $attribute): string
    {
        $stock = '';
        if ($attribute == 'stock') {
            if (!$this->inventoryTracked) {
                $stock = '∞';
            } else {
                $stock = $this->getStock();
            }
        }

        $dimensions = [];
        if ($attribute === 'dimensions') {
            $dimensions = array_filter([
                $this->length,
                $this->width,
                $this->height,
            ]);
        }

        if ($attribute === 'priceView') {
            $price = $this->basePriceAsCurrency;
            if ($this->getBasePromotionalPrice() && $this->getBasePromotionalPrice() < $this->getBasePrice()) {
                $price = Html::tag('del', $price, ['style' => 'opacity: .5']) . ' ' . $this->basePromotionalPriceAsCurrency;
            }

            return $price;
        }

        if ($attribute === 'availableForPurchase') {
            if ($this->availableForPurchase) {
                $icon = Html::tag('span', '', [
                    'class' => 'checkbox-icon',
                    'role' => 'img',
                    'title' => t('Enabled'),
                    'aria' => [
                        'label' => t('Enabled'),
                    ],
                ]);
                return $icon . Html::tag('span', ' ' . t('Available for purchase', category: 'commerce'), [
                    'class' => 'card-only-label',
                    'style' => 'display:none;',
                ]) . Html::tag('style', '.card-content .card-only-label { display: inline !important; }');
            }
        }

        return match ($attribute) {
            'sku' => (string)Html::encode($this->getSkuAsText()),
            'price' => $this->basePriceAsCurrency,
            'promotionalPrice' => $this->basePromotionalPrice !== null ? $this->basePromotionalPriceAsCurrency : '',
            'weight' => $this->weight !== null ? I18N::getFormatter()->asDecimal($this->$attribute) . ' ' . Plugin::getInstance()->getSettings()->weightUnits : '',
            'length' => $this->length !== null ? I18N::getFormatter()->asDecimal($this->$attribute) . ' ' . Plugin::getInstance()->getSettings()->dimensionUnits : '',
            'width' => $this->width !== null ? I18N::getFormatter()->asDecimal($this->$attribute) . ' ' . Plugin::getInstance()->getSettings()->dimensionUnits : '',
            'height' => $this->height !== null ? I18N::getFormatter()->asDecimal($this->$attribute) . ' ' . Plugin::getInstance()->getSettings()->dimensionUnits : '',
            'minQty' => (string)$this->minQty,
            'maxQty' => (string)$this->maxQty,
            'stock' => $this::hasInventory() ? $stock : '',
            'dimensions' => !empty($dimensions) ? implode(' x ', $dimensions) . ' ' . Plugin::getInstance()->getSettings()->dimensionUnits : '',
            default => parent::attributeHtml($attribute),
        };
    }

    protected static function defineTableAttributes(): array
    {
        return array_merge(parent::defineTableAttributes(), [
            'title' => ['label' => t('Title', category: 'commerce')],
            'sku' => ['label' => t('SKU', category: 'commerce')],
            'price' => ['label' => t('Price', category: 'commerce')],
            'promotionalPrice' => ['label' => t('Promotional Price', category: 'commerce')],
            'width' => ['label' => t('Width ({unit})', ['unit' => Plugin::getInstance()->getSettings()->dimensionUnits], category: 'commerce')],
            'height' => ['label' => t('Height ({unit})', ['unit' => Plugin::getInstance()->getSettings()->dimensionUnits], category: 'commerce')],
            'length' => ['label' => t('Length ({unit})', ['unit' => Plugin::getInstance()->getSettings()->dimensionUnits], category: 'commerce')],
            'weight' => ['label' => t('Weight ({unit})', ['unit' => Plugin::getInstance()->getSettings()->weightUnits], category: 'commerce')],
            'stock' => ['label' => t('Stock', category: 'commerce')],
            'minQty' => ['label' => t('Min Qty', category: 'commerce')],
            'maxQty' => ['label' => t('Max Qty', category: 'commerce')],
            'availableForPurchase' => ['label' => t('Available for purchase', category: 'commerce')],
            'inventoryTracked' => ['label' => t('Inventory Tracked', category: 'commerce')],
        ]);
    }

    protected static function defineDefaultTableAttributes(string $source): array
    {
        return [
            'sku',
            'price',
        ];
    }

    public static function hasInventory(): bool
    {
        return true;
    }

    public static function attributePreviewHtml(array $attribute): mixed
    {
        return match ($attribute['value']) {
            'sku', 'priceView', 'dimensions', 'weight' => $attribute['placeholder'],
            'availableForPurchase', 'promotable' => Html::tag('span', '', [
                    'class' => 'checkbox-icon',
                    'role' => 'img',
                    'title' => $attribute['label'],
                    'aria' => [
                        'label' => $attribute['label'],
                    ],
                ]) .
                Html::tag('span', $attribute['label'], [
                    'class' => 'checkbox-preview-label',
                ]),
            default => parent::attributePreviewHtml($attribute)
        };
    }

    protected static function defineDefaultCardAttributes(): array
    {
        return array_merge(parent::defineDefaultCardAttributes(), [
            'sku',
            'priceView',
        ]);
    }

    protected static function defineCardAttributes(): array
    {
        return array_merge(parent::defineCardAttributes(), [
            'availableForPurchase' => [
                'label' => t('Available for purchase', category: 'commerce'),
            ],
            'basePrice' => [
                'label' => t('Base Price', category: 'commerce'),
                'placeholder' => '¤' . I18N::getFormatter()->asDecimal(123.99),
            ],
            'basePromotionalPrice' => [
                'label' => t('Base Promotional Price', category: 'commerce'),
                'placeholder' => '¤' . I18N::getFormatter()->asDecimal(123.99),
            ],
            'dimensions' => [
                'label' => t('Dimensions', category: 'commerce'),
                'placeholder' => '1 x 2 x 3 ' . Plugin::getInstance()->getSettings()->dimensionUnits,
            ],
            'priceView' => [
                'label' => t('Price', category: 'commerce'),
                'placeholder' => Html::tag('del', '¤' . I18N::getFormatter()->asDecimal(199.99), ['style' => 'opacity: .5']) . ' ¤' . I18N::getFormatter()->asDecimal(123.99),
            ],
            'promotable' => [
                'label' => t('Promotable', category: 'commerce'),
            ],
            'sku' => [
                'label' => t('SKU', category: 'commerce'),
                'placeholder' => Html::tag('code', 'SKU123'),
            ],
            'stock' => [
                'label' => t('Stock', category: 'commerce'),
                'placeholder' => 10,
            ],
            'weight' => [
                'label' => t('Weight', category: 'commerce'),
                'placeholder' => 123 . Plugin::getInstance()->getSettings()->weightUnits,
            ],
        ]);
    }

    protected static function defineSortOptions(): array
    {
        return [
            'title' => t('Title', category: 'commerce'),
            'sku' => t('SKU', category: 'commerce'),
        ];
    }

    protected static function defineSearchableAttributes(): array
    {
        return [...parent::defineSearchableAttributes(), ...[
            'description',
            'sku',
            'price',
            'width',
            'height',
            'length',
            'weight',
            'minQty',
            'maxQty',
        ]];
    }

    /**
     * Reloads any sales applicable to the purchasable.
     *
     * @internal
     */
    public function loadSales(?Order $order = null): void
    {
        // Default the sales and salePrice to the original price without any sales
        $this->_sales = [];

        if ($this->getId()) {
            $this->_sales = app(Sales::class)->getSalesForPurchasable($this, $order);
            $this->_salesPrice = app(Sales::class)->getSalePriceForPurchasable($this, $order);
        }
    }
}
