codecov:
  branch: develop
  require_ci_to_pass: yes
coverage:
  range: "20...100"
  round: down
  precision: 2
  status:
    project:
      default:
        threshold: .1
        base: pr
  notify:
      slack:
        default:
          url: "secret:hbWp/me8PnbBJSIUO451vp1r/ckaonSCbx/yN43zapDfJ1b9X/K6rgqTN4PfPmujZZJ7Jz8+k9ql4p9aWKpmZbP/Yqd0wOcZchYKKKBiXHopaa53xw/DJ4o16NYpwSHz6gYKku89r0/teupDUosc4KBlEPwl09Rx/ak5/R/dXXU="
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
comment: off
ignore:
  - "src/etc"
  - "src/migrations"
  - "src/templates"
  - "src/translations"
  - "src/web/assets"
  - "docs"
  - "templates"
  - "tests"
  - "vendor"