<?php
/**
 * @link https://craftcms.com/
 * @copyright Copyright (c) Pixel & Tonic, Inc.
 * @license https://craftcms.github.io/license/
 */

namespace craft\commerce\events;

use craft\commerce\elements\Order;
use craft\commerce\models\Discount;
use craft\commerce\models\OrderAdjustment;
use craft\events\CancelableEvent;

/**
 * Class DiscountAdjustmentsEvent
 *
 * @author Pixel & Tonic, Inc. <support@pixelandtonic.com>
 * @since 2.0
 */
class DiscountAdjustmentsEvent extends CancelableEvent
{
    /**
     * @var Order The order the discount generated the adjustments for. Do not mutate.
     */
    public $order;

    /**
     * @var Discount The discount that matched.
     */
    public $discount;

    /**
     * @var OrderAdjustment[] The adjustments generated by the discount.
     */
    public $adjustments;
}
