<?php
// Using the data from moneyphp/money until we actually move to the package in Craft Commerce 2
// https://raw.githubusercontent.com/moneyphp/money/master/resources/currency.php

return ['AFN' => ['alphabeticCode' => 'AFN',
                  'currency'       => 'Afghani',
                  'entity'         => 'AFGHANISTAN',
                  'minorUnit'      => 2,
                  'numericCode'    => 971,],
        'EUR' => ['alphabeticCode' => 'EUR',
                  'currency'       => 'Euro',
                  'entity'         => 'SPAIN',
                  'minorUnit'      => 2,
                  'numericCode'    => 978,],
        'ALL' => ['alphabeticCode' => 'ALL',
                  'currency'       => 'Lek',
                  'entity'         => 'ALBANIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 8,],
        'DZD' => ['alphabeticCode' => 'DZD',
                  'currency'       => 'Algerian Dinar',
                  'entity'         => 'ALGERIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 12,],
        'USD' => ['alphabeticCode' => 'USD',
                  'currency'       => 'US Dollar',
                  'entity'         => 'VIRGIN ISLANDS (U.S.)',
                  'minorUnit'      => 2,
                  'numericCode'    => 840,],
        'AOA' => ['alphabeticCode' => 'AOA',
                  'currency'       => 'Kwanza',
                  'entity'         => 'ANGOLA',
                  'minorUnit'      => 2,
                  'numericCode'    => 973,],
        'XCD' => ['alphabeticCode' => 'XCD',
                  'currency'       => 'East Caribbean Dollar',
                  'entity'         => 'SAINT VINCENT AND THE GRENADINES',
                  'minorUnit'      => 2,
                  'numericCode'    => 951,],
        'ARS' => ['alphabeticCode' => 'ARS',
                  'currency'       => 'Argentine Peso',
                  'entity'         => 'ARGENTINA',
                  'minorUnit'      => 2,
                  'numericCode'    => 32,],
        'AMD' => ['alphabeticCode' => 'AMD',
                  'currency'       => 'Armenian Dram',
                  'entity'         => 'ARMENIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 51,],
        'AWG' => ['alphabeticCode' => 'AWG',
                  'currency'       => 'Aruban Florin',
                  'entity'         => 'ARUBA',
                  'minorUnit'      => 2,
                  'numericCode'    => 533,],
        'AUD' => ['alphabeticCode' => 'AUD',
                  'currency'       => 'Australian Dollar',
                  'entity'         => 'TUVALU',
                  'minorUnit'      => 2,
                  'numericCode'    => 36,],
        'AZN' => ['alphabeticCode' => 'AZN',
                  'currency'       => 'Azerbaijanian Manat',
                  'entity'         => 'AZERBAIJAN',
                  'minorUnit'      => 2,
                  'numericCode'    => 944,],
        'BSD' => ['alphabeticCode' => 'BSD',
                  'currency'       => 'Bahamian Dollar',
                  'entity'         => 'BAHAMAS (THE)',
                  'minorUnit'      => 2,
                  'numericCode'    => 44,],
        'BHD' => ['alphabeticCode' => 'BHD',
                  'currency'       => 'Bahraini Dinar',
                  'entity'         => 'BAHRAIN',
                  'minorUnit'      => 3,
                  'numericCode'    => 48,],
        'BDT' => ['alphabeticCode' => 'BDT',
                  'currency'       => 'Taka',
                  'entity'         => 'BANGLADESH',
                  'minorUnit'      => 2,
                  'numericCode'    => 50,],
        'BBD' => ['alphabeticCode' => 'BBD',
                  'currency'       => 'Barbados Dollar',
                  'entity'         => 'BARBADOS',
                  'minorUnit'      => 2,
                  'numericCode'    => 52,],
        'BYN' => ['alphabeticCode' => 'BYN',
                  'currency'       => 'Belarusian Ruble',
                  'entity'         => 'BELARUS',
                  'minorUnit'      => 2,
                  'numericCode'    => 933,],
        'BYR' => ['alphabeticCode' => 'BYR',
                  'currency'       => 'Belarusian Ruble',
                  'entity'         => 'BELARUS',
                  'minorUnit'      => 0,
                  'numericCode'    => 974,],
        'BZD' => ['alphabeticCode' => 'BZD',
                  'currency'       => 'Belize Dollar',
                  'entity'         => 'BELIZE',
                  'minorUnit'      => 2,
                  'numericCode'    => 84,],
        'XOF' => ['alphabeticCode' => 'XOF',
                  'currency'       => 'CFA Franc BCEAO',
                  'entity'         => 'TOGO',
                  'minorUnit'      => 0,
                  'numericCode'    => 952,],
        'BMD' => ['alphabeticCode' => 'BMD',
                  'currency'       => 'Bermudian Dollar',
                  'entity'         => 'BERMUDA',
                  'minorUnit'      => 2,
                  'numericCode'    => 60,],
        'INR' => ['alphabeticCode' => 'INR',
                  'currency'       => 'Indian Rupee',
                  'entity'         => 'INDIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 356,],
        'BTN' => ['alphabeticCode' => 'BTN',
                  'currency'       => 'Ngultrum',
                  'entity'         => 'BHUTAN',
                  'minorUnit'      => 2,
                  'numericCode'    => 64,],
        'BOB' => ['alphabeticCode' => 'BOB',
                  'currency'       => 'Boliviano',
                  'entity'         => 'BOLIVIA (PLURINATIONAL STATE OF)',
                  'minorUnit'      => 2,
                  'numericCode'    => 68,],
        'BOV' => ['alphabeticCode' => 'BOV',
                  'currency'       => 'Mvdol',
                  'entity'         => 'BOLIVIA (PLURINATIONAL STATE OF)',
                  'minorUnit'      => 2,
                  'numericCode'    => 984,],
        'BAM' => ['alphabeticCode' => 'BAM',
                  'currency'       => 'Convertible Mark',
                  'entity'         => 'BOSNIA AND HERZEGOVINA',
                  'minorUnit'      => 2,
                  'numericCode'    => 977,],
        'BWP' => ['alphabeticCode' => 'BWP',
                  'currency'       => 'Pula',
                  'entity'         => 'BOTSWANA',
                  'minorUnit'      => 2,
                  'numericCode'    => 72,],
        'NOK' => ['alphabeticCode' => 'NOK',
                  'currency'       => 'Norwegian Krone',
                  'entity'         => 'SVALBARD AND JAN MAYEN',
                  'minorUnit'      => 2,
                  'numericCode'    => 578,],
        'BRL' => ['alphabeticCode' => 'BRL',
                  'currency'       => 'Brazilian Real',
                  'entity'         => 'BRAZIL',
                  'minorUnit'      => 2,
                  'numericCode'    => 986,],
        'BND' => ['alphabeticCode' => 'BND',
                  'currency'       => 'Brunei Dollar',
                  'entity'         => 'BRUNEI DARUSSALAM',
                  'minorUnit'      => 2,
                  'numericCode'    => 96,],
        'BGN' => ['alphabeticCode' => 'BGN',
                  'currency'       => 'Bulgarian Lev',
                  'entity'         => 'BULGARIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 975,],
        'BIF' => ['alphabeticCode' => 'BIF',
                  'currency'       => 'Burundi Franc',
                  'entity'         => 'BURUNDI',
                  'minorUnit'      => 0,
                  'numericCode'    => 108,],
        'CVE' => ['alphabeticCode' => 'CVE',
                  'currency'       => 'Cabo Verde Escudo',
                  'entity'         => 'CABO VERDE',
                  'minorUnit'      => 2,
                  'numericCode'    => 132,],
        'KHR' => ['alphabeticCode' => 'KHR',
                  'currency'       => 'Riel',
                  'entity'         => 'CAMBODIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 116,],
        'XAF' => ['alphabeticCode' => 'XAF',
                  'currency'       => 'CFA Franc BEAC',
                  'entity'         => 'GABON',
                  'minorUnit'      => 0,
                  'numericCode'    => 950,],
        'CAD' => ['alphabeticCode' => 'CAD',
                  'currency'       => 'Canadian Dollar',
                  'entity'         => 'CANADA',
                  'minorUnit'      => 2,
                  'numericCode'    => 124,],
        'KYD' => ['alphabeticCode' => 'KYD',
                  'currency'       => 'Cayman Islands Dollar',
                  'entity'         => 'CAYMAN ISLANDS (THE)',
                  'minorUnit'      => 2,
                  'numericCode'    => 136,],
        'CLP' => ['alphabeticCode' => 'CLP',
                  'currency'       => 'Chilean Peso',
                  'entity'         => 'CHILE',
                  'minorUnit'      => 0,
                  'numericCode'    => 152,],
        'CLF' => ['alphabeticCode' => 'CLF',
                  'currency'       => 'Unidad de Fomento',
                  'entity'         => 'CHILE',
                  'minorUnit'      => 4,
                  'numericCode'    => 990,],
        'CNY' => ['alphabeticCode' => 'CNY',
                  'currency'       => 'Yuan Renminbi',
                  'entity'         => 'CHINA',
                  'minorUnit'      => 2,
                  'numericCode'    => 156,],
        'COP' => ['alphabeticCode' => 'COP',
                  'currency'       => 'Colombian Peso',
                  'entity'         => 'COLOMBIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 170,],
        'COU' => ['alphabeticCode' => 'COU',
                  'currency'       => 'Unidad de Valor Real',
                  'entity'         => 'COLOMBIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 970,],
        'KMF' => ['alphabeticCode' => 'KMF',
                  'currency'       => 'Comoro Franc',
                  'entity'         => 'COMOROS (THE)',
                  'minorUnit'      => 0,
                  'numericCode'    => 174,],
        'CDF' => ['alphabeticCode' => 'CDF',
                  'currency'       => 'Congolese Franc',
                  'entity'         => 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
                  'minorUnit'      => 2,
                  'numericCode'    => 976,],
        'NZD' => ['alphabeticCode' => 'NZD',
                  'currency'       => 'New Zealand Dollar',
                  'entity'         => 'TOKELAU',
                  'minorUnit'      => 2,
                  'numericCode'    => 554,],
        'CRC' => ['alphabeticCode' => 'CRC',
                  'currency'       => 'Costa Rican Colon',
                  'entity'         => 'COSTA RICA',
                  'minorUnit'      => 2,
                  'numericCode'    => 188,],
        'HRK' => ['alphabeticCode' => 'HRK',
                  'currency'       => 'Kuna',
                  'entity'         => 'CROATIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 191,],
        'CUP' => ['alphabeticCode' => 'CUP',
                  'currency'       => 'Cuban Peso',
                  'entity'         => 'CUBA',
                  'minorUnit'      => 2,
                  'numericCode'    => 192,],
        'CUC' => ['alphabeticCode' => 'CUC',
                  'currency'       => 'Peso Convertible',
                  'entity'         => 'CUBA',
                  'minorUnit'      => 2,
                  'numericCode'    => 931,],
        'ANG' => ['alphabeticCode' => 'ANG',
                  'currency'       => 'Netherlands Antillean Guilder',
                  'entity'         => 'SINT MAARTEN (DUTCH PART)',
                  'minorUnit'      => 2,
                  'numericCode'    => 532,],
        'CZK' => ['alphabeticCode' => 'CZK',
                  'currency'       => 'Czech Koruna',
                  'entity'         => 'CZECH REPUBLIC (THE)',
                  'minorUnit'      => 2,
                  'numericCode'    => 203,],
        'DKK' => ['alphabeticCode' => 'DKK',
                  'currency'       => 'Danish Krone',
                  'entity'         => 'GREENLAND',
                  'minorUnit'      => 2,
                  'numericCode'    => 208,],
        'DJF' => ['alphabeticCode' => 'DJF',
                  'currency'       => 'Djibouti Franc',
                  'entity'         => 'DJIBOUTI',
                  'minorUnit'      => 0,
                  'numericCode'    => 262,],
        'DOP' => ['alphabeticCode' => 'DOP',
                  'currency'       => 'Dominican Peso',
                  'entity'         => 'DOMINICAN REPUBLIC (THE)',
                  'minorUnit'      => 2,
                  'numericCode'    => 214,],
        'EGP' => ['alphabeticCode' => 'EGP',
                  'currency'       => 'Egyptian Pound',
                  'entity'         => 'EGYPT',
                  'minorUnit'      => 2,
                  'numericCode'    => 818,],
        'SVC' => ['alphabeticCode' => 'SVC',
                  'currency'       => 'El Salvador Colon',
                  'entity'         => 'EL SALVADOR',
                  'minorUnit'      => 2,
                  'numericCode'    => 222,],
        'ERN' => ['alphabeticCode' => 'ERN',
                  'currency'       => 'Nakfa',
                  'entity'         => 'ERITREA',
                  'minorUnit'      => 2,
                  'numericCode'    => 232,],
        'ETB' => ['alphabeticCode' => 'ETB',
                  'currency'       => 'Ethiopian Birr',
                  'entity'         => 'ETHIOPIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 230,],
        'FKP' => ['alphabeticCode' => 'FKP',
                  'currency'       => 'Falkland Islands Pound',
                  'entity'         => 'FALKLAND ISLANDS (THE) [MALVINAS]',
                  'minorUnit'      => 2,
                  'numericCode'    => 238,],
        'FJD' => ['alphabeticCode' => 'FJD',
                  'currency'       => 'Fiji Dollar',
                  'entity'         => 'FIJI',
                  'minorUnit'      => 2,
                  'numericCode'    => 242,],
        'XPF' => ['alphabeticCode' => 'XPF',
                  'currency'       => 'CFP Franc',
                  'entity'         => 'WALLIS AND FUTUNA',
                  'minorUnit'      => 0,
                  'numericCode'    => 953,],
        'GMD' => ['alphabeticCode' => 'GMD',
                  'currency'       => 'Dalasi',
                  'entity'         => 'GAMBIA (THE)',
                  'minorUnit'      => 2,
                  'numericCode'    => 270,],
        'GEL' => ['alphabeticCode' => 'GEL',
                  'currency'       => 'Lari',
                  'entity'         => 'GEORGIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 981,],
        'GHS' => ['alphabeticCode' => 'GHS',
                  'currency'       => 'Ghana Cedi',
                  'entity'         => 'GHANA',
                  'minorUnit'      => 2,
                  'numericCode'    => 936,],
        'GIP' => ['alphabeticCode' => 'GIP',
                  'currency'       => 'Gibraltar Pound',
                  'entity'         => 'GIBRALTAR',
                  'minorUnit'      => 2,
                  'numericCode'    => 292,],
        'GTQ' => ['alphabeticCode' => 'GTQ',
                  'currency'       => 'Quetzal',
                  'entity'         => 'GUATEMALA',
                  'minorUnit'      => 2,
                  'numericCode'    => 320,],
        'GBP' => ['alphabeticCode' => 'GBP',
                  'currency'       => 'Pound Sterling',
                  'entity'         => 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
                  'minorUnit'      => 2,
                  'numericCode'    => 826,],
        'GNF' => ['alphabeticCode' => 'GNF',
                  'currency'       => 'Guinea Franc',
                  'entity'         => 'GUINEA',
                  'minorUnit'      => 0,
                  'numericCode'    => 324,],
        'GYD' => ['alphabeticCode' => 'GYD',
                  'currency'       => 'Guyana Dollar',
                  'entity'         => 'GUYANA',
                  'minorUnit'      => 2,
                  'numericCode'    => 328,],
        'HTG' => ['alphabeticCode' => 'HTG',
                  'currency'       => 'Gourde',
                  'entity'         => 'HAITI',
                  'minorUnit'      => 2,
                  'numericCode'    => 332,],
        'HNL' => ['alphabeticCode' => 'HNL',
                  'currency'       => 'Lempira',
                  'entity'         => 'HONDURAS',
                  'minorUnit'      => 2,
                  'numericCode'    => 340,],
        'HKD' => ['alphabeticCode' => 'HKD',
                  'currency'       => 'Hong Kong Dollar',
                  'entity'         => 'HONG KONG',
                  'minorUnit'      => 2,
                  'numericCode'    => 344,],
        'HUF' => ['alphabeticCode' => 'HUF',
                  'currency'       => 'Forint',
                  'entity'         => 'HUNGARY',
                  'minorUnit'      => 2,
                  'numericCode'    => 348,],
        'ISK' => ['alphabeticCode' => 'ISK',
                  'currency'       => 'Iceland Krona',
                  'entity'         => 'ICELAND',
                  'minorUnit'      => 0,
                  'numericCode'    => 352,],
        'IDR' => ['alphabeticCode' => 'IDR',
                  'currency'       => 'Rupiah',
                  'entity'         => 'INDONESIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 360,],
        'XDR' => ['alphabeticCode' => 'XDR',
                  'currency'       => 'SDR (Special Drawing Right)',
                  'entity'         => 'INTERNATIONAL MONETARY FUND (IMF) ',
                  'minorUnit'      => 0,
                  'numericCode'    => 960,],
        'IRR' => ['alphabeticCode' => 'IRR',
                  'currency'       => 'Iranian Rial',
                  'entity'         => 'IRAN (ISLAMIC REPUBLIC OF)',
                  'minorUnit'      => 2,
                  'numericCode'    => 364,],
        'IQD' => ['alphabeticCode' => 'IQD',
                  'currency'       => 'Iraqi Dinar',
                  'entity'         => 'IRAQ',
                  'minorUnit'      => 3,
                  'numericCode'    => 368,],
        'ILS' => ['alphabeticCode' => 'ILS',
                  'currency'       => 'New Israeli Sheqel',
                  'entity'         => 'ISRAEL',
                  'minorUnit'      => 2,
                  'numericCode'    => 376,],
        'JMD' => ['alphabeticCode' => 'JMD',
                  'currency'       => 'Jamaican Dollar',
                  'entity'         => 'JAMAICA',
                  'minorUnit'      => 2,
                  'numericCode'    => 388,],
        'JPY' => ['alphabeticCode' => 'JPY',
                  'currency'       => 'Yen',
                  'entity'         => 'JAPAN',
                  'minorUnit'      => 0,
                  'numericCode'    => 392,],
        'JOD' => ['alphabeticCode' => 'JOD',
                  'currency'       => 'Jordanian Dinar',
                  'entity'         => 'JORDAN',
                  'minorUnit'      => 3,
                  'numericCode'    => 400,],
        'KZT' => ['alphabeticCode' => 'KZT',
                  'currency'       => 'Tenge',
                  'entity'         => 'KAZAKHSTAN',
                  'minorUnit'      => 2,
                  'numericCode'    => 398,],
        'KES' => ['alphabeticCode' => 'KES',
                  'currency'       => 'Kenyan Shilling',
                  'entity'         => 'KENYA',
                  'minorUnit'      => 2,
                  'numericCode'    => 404,],
        'KPW' => ['alphabeticCode' => 'KPW',
                  'currency'       => 'North Korean Won',
                  'entity'         => 'KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)',
                  'minorUnit'      => 2,
                  'numericCode'    => 408,],
        'KRW' => ['alphabeticCode' => 'KRW',
                  'currency'       => 'Won',
                  'entity'         => 'KOREA (THE REPUBLIC OF)',
                  'minorUnit'      => 0,
                  'numericCode'    => 410,],
        'KWD' => ['alphabeticCode' => 'KWD',
                  'currency'       => 'Kuwaiti Dinar',
                  'entity'         => 'KUWAIT',
                  'minorUnit'      => 3,
                  'numericCode'    => 414,],
        'KGS' => ['alphabeticCode' => 'KGS',
                  'currency'       => 'Som',
                  'entity'         => 'KYRGYZSTAN',
                  'minorUnit'      => 2,
                  'numericCode'    => 417,],
        'LAK' => ['alphabeticCode' => 'LAK',
                  'currency'       => 'Kip',
                  'entity'         => 'LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)',
                  'minorUnit'      => 2,
                  'numericCode'    => 418,],
        'LBP' => ['alphabeticCode' => 'LBP',
                  'currency'       => 'Lebanese Pound',
                  'entity'         => 'LEBANON',
                  'minorUnit'      => 2,
                  'numericCode'    => 422,],
        'LSL' => ['alphabeticCode' => 'LSL',
                  'currency'       => 'Loti',
                  'entity'         => 'LESOTHO',
                  'minorUnit'      => 2,
                  'numericCode'    => 426,],
        'ZAR' => ['alphabeticCode' => 'ZAR',
                  'currency'       => 'Rand',
                  'entity'         => 'SOUTH AFRICA',
                  'minorUnit'      => 2,
                  'numericCode'    => 710,],
        'LRD' => ['alphabeticCode' => 'LRD',
                  'currency'       => 'Liberian Dollar',
                  'entity'         => 'LIBERIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 430,],
        'LYD' => ['alphabeticCode' => 'LYD',
                  'currency'       => 'Libyan Dinar',
                  'entity'         => 'LIBYA',
                  'minorUnit'      => 3,
                  'numericCode'    => 434,],
        'CHF' => ['alphabeticCode' => 'CHF',
                  'currency'       => 'Swiss Franc',
                  'entity'         => 'SWITZERLAND',
                  'minorUnit'      => 2,
                  'numericCode'    => 756,],
        'MOP' => ['alphabeticCode' => 'MOP',
                  'currency'       => 'Pataca',
                  'entity'         => 'MACAO',
                  'minorUnit'      => 2,
                  'numericCode'    => 446,],
        'MKD' => ['alphabeticCode' => 'MKD',
                  'currency'       => 'Denar',
                  'entity'         => 'MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)',
                  'minorUnit'      => 2,
                  'numericCode'    => 807,],
        'MGA' => ['alphabeticCode' => 'MGA',
                  'currency'       => 'Malagasy Ariary',
                  'entity'         => 'MADAGASCAR',
                  'minorUnit'      => 2,
                  'numericCode'    => 969,],
        'MWK' => ['alphabeticCode' => 'MWK',
                  'currency'       => 'Malawi Kwacha',
                  'entity'         => 'MALAWI',
                  'minorUnit'      => 2,
                  'numericCode'    => 454,],
        'MYR' => ['alphabeticCode' => 'MYR',
                  'currency'       => 'Malaysian Ringgit',
                  'entity'         => 'MALAYSIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 458,],
        'MVR' => ['alphabeticCode' => 'MVR',
                  'currency'       => 'Rufiyaa',
                  'entity'         => 'MALDIVES',
                  'minorUnit'      => 2,
                  'numericCode'    => 462,],
        'MRO' => ['alphabeticCode' => 'MRO',
                  'currency'       => 'Ouguiya',
                  'entity'         => 'MAURITANIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 478,],
        'MUR' => ['alphabeticCode' => 'MUR',
                  'currency'       => 'Mauritius Rupee',
                  'entity'         => 'MAURITIUS',
                  'minorUnit'      => 2,
                  'numericCode'    => 480,],
        'XUA' => ['alphabeticCode' => 'XUA',
                  'currency'       => 'ADB Unit of Account',
                  'entity'         => 'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP',
                  'minorUnit'      => 0,
                  'numericCode'    => 965,],
        'MXN' => ['alphabeticCode' => 'MXN',
                  'currency'       => 'Mexican Peso',
                  'entity'         => 'MEXICO',
                  'minorUnit'      => 2,
                  'numericCode'    => 484,],
        'MXV' => ['alphabeticCode' => 'MXV',
                  'currency'       => 'Mexican Unidad de Inversion (UDI)',
                  'entity'         => 'MEXICO',
                  'minorUnit'      => 2,
                  'numericCode'    => 979,],
        'MDL' => ['alphabeticCode' => 'MDL',
                  'currency'       => 'Moldovan Leu',
                  'entity'         => 'MOLDOVA (THE REPUBLIC OF)',
                  'minorUnit'      => 2,
                  'numericCode'    => 498,],
        'MNT' => ['alphabeticCode' => 'MNT',
                  'currency'       => 'Tugrik',
                  'entity'         => 'MONGOLIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 496,],
        'MAD' => ['alphabeticCode' => 'MAD',
                  'currency'       => 'Moroccan Dirham',
                  'entity'         => 'WESTERN SAHARA',
                  'minorUnit'      => 2,
                  'numericCode'    => 504,],
        'MZN' => ['alphabeticCode' => 'MZN',
                  'currency'       => 'Mozambique Metical',
                  'entity'         => 'MOZAMBIQUE',
                  'minorUnit'      => 2,
                  'numericCode'    => 943,],
        'MMK' => ['alphabeticCode' => 'MMK',
                  'currency'       => 'Kyat',
                  'entity'         => 'MYANMAR',
                  'minorUnit'      => 2,
                  'numericCode'    => 104,],
        'NAD' => ['alphabeticCode' => 'NAD',
                  'currency'       => 'Namibia Dollar',
                  'entity'         => 'NAMIBIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 516,],
        'NPR' => ['alphabeticCode' => 'NPR',
                  'currency'       => 'Nepalese Rupee',
                  'entity'         => 'NEPAL',
                  'minorUnit'      => 2,
                  'numericCode'    => 524,],
        'NIO' => ['alphabeticCode' => 'NIO',
                  'currency'       => 'Cordoba Oro',
                  'entity'         => 'NICARAGUA',
                  'minorUnit'      => 2,
                  'numericCode'    => 558,],
        'NGN' => ['alphabeticCode' => 'NGN',
                  'currency'       => 'Naira',
                  'entity'         => 'NIGERIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 566,],
        'OMR' => ['alphabeticCode' => 'OMR',
                  'currency'       => 'Rial Omani',
                  'entity'         => 'OMAN',
                  'minorUnit'      => 3,
                  'numericCode'    => 512,],
        'PKR' => ['alphabeticCode' => 'PKR',
                  'currency'       => 'Pakistan Rupee',
                  'entity'         => 'PAKISTAN',
                  'minorUnit'      => 2,
                  'numericCode'    => 586,],
        'PAB' => ['alphabeticCode' => 'PAB',
                  'currency'       => 'Balboa',
                  'entity'         => 'PANAMA',
                  'minorUnit'      => 2,
                  'numericCode'    => 590,],
        'PGK' => ['alphabeticCode' => 'PGK',
                  'currency'       => 'Kina',
                  'entity'         => 'PAPUA NEW GUINEA',
                  'minorUnit'      => 2,
                  'numericCode'    => 598,],
        'PYG' => ['alphabeticCode' => 'PYG',
                  'currency'       => 'Guarani',
                  'entity'         => 'PARAGUAY',
                  'minorUnit'      => 0,
                  'numericCode'    => 600,],
        'PEN' => ['alphabeticCode' => 'PEN',
                  'currency'       => 'Sol',
                  'entity'         => 'PERU',
                  'minorUnit'      => 2,
                  'numericCode'    => 604,],
        'PHP' => ['alphabeticCode' => 'PHP',
                  'currency'       => 'Philippine Peso',
                  'entity'         => 'PHILIPPINES (THE)',
                  'minorUnit'      => 2,
                  'numericCode'    => 608,],
        'PLN' => ['alphabeticCode' => 'PLN',
                  'currency'       => 'Zloty',
                  'entity'         => 'POLAND',
                  'minorUnit'      => 2,
                  'numericCode'    => 985,],
        'QAR' => ['alphabeticCode' => 'QAR',
                  'currency'       => 'Qatari Rial',
                  'entity'         => 'QATAR',
                  'minorUnit'      => 2,
                  'numericCode'    => 634,],
        'RON' => ['alphabeticCode' => 'RON',
                  'currency'       => 'Romanian Leu',
                  'entity'         => 'ROMANIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 946,],
        'RUB' => ['alphabeticCode' => 'RUB',
                  'currency'       => 'Russian Ruble',
                  'entity'         => 'RUSSIAN FEDERATION (THE)',
                  'minorUnit'      => 2,
                  'numericCode'    => 643,],
        'RWF' => ['alphabeticCode' => 'RWF',
                  'currency'       => 'Rwanda Franc',
                  'entity'         => 'RWANDA',
                  'minorUnit'      => 0,
                  'numericCode'    => 646,],
        'SHP' => ['alphabeticCode' => 'SHP',
                  'currency'       => 'Saint Helena Pound',
                  'entity'         => 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
                  'minorUnit'      => 2,
                  'numericCode'    => 654,],
        'WST' => ['alphabeticCode' => 'WST',
                  'currency'       => 'Tala',
                  'entity'         => 'SAMOA',
                  'minorUnit'      => 2,
                  'numericCode'    => 882,],
        'STD' => ['alphabeticCode' => 'STD',
                  'currency'       => 'Dobra',
                  'entity'         => 'SAO TOME AND PRINCIPE',
                  'minorUnit'      => 2,
                  'numericCode'    => 678,],
        'SAR' => ['alphabeticCode' => 'SAR',
                  'currency'       => 'Saudi Riyal',
                  'entity'         => 'SAUDI ARABIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 682,],
        'RSD' => ['alphabeticCode' => 'RSD',
                  'currency'       => 'Serbian Dinar',
                  'entity'         => 'SERBIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 941,],
        'SCR' => ['alphabeticCode' => 'SCR',
                  'currency'       => 'Seychelles Rupee',
                  'entity'         => 'SEYCHELLES',
                  'minorUnit'      => 2,
                  'numericCode'    => 690,],
        'SLL' => ['alphabeticCode' => 'SLL',
                  'currency'       => 'Leone',
                  'entity'         => 'SIERRA LEONE',
                  'minorUnit'      => 2,
                  'numericCode'    => 694,],
        'SGD' => ['alphabeticCode' => 'SGD',
                  'currency'       => 'Singapore Dollar',
                  'entity'         => 'SINGAPORE',
                  'minorUnit'      => 2,
                  'numericCode'    => 702,],
        'XSU' => ['alphabeticCode' => 'XSU',
                  'currency'       => 'Sucre',
                  'entity'         => 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS SUCRE',
                  'minorUnit'      => 0,
                  'numericCode'    => 994,],
        'SBD' => ['alphabeticCode' => 'SBD',
                  'currency'       => 'Solomon Islands Dollar',
                  'entity'         => 'SOLOMON ISLANDS',
                  'minorUnit'      => 2,
                  'numericCode'    => 90,],
        'SOS' => ['alphabeticCode' => 'SOS',
                  'currency'       => 'Somali Shilling',
                  'entity'         => 'SOMALIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 706,],
        'SSP' => ['alphabeticCode' => 'SSP',
                  'currency'       => 'South Sudanese Pound',
                  'entity'         => 'SOUTH SUDAN',
                  'minorUnit'      => 2,
                  'numericCode'    => 728,],
        'LKR' => ['alphabeticCode' => 'LKR',
                  'currency'       => 'Sri Lanka Rupee',
                  'entity'         => 'SRI LANKA',
                  'minorUnit'      => 2,
                  'numericCode'    => 144,],
        'SDG' => ['alphabeticCode' => 'SDG',
                  'currency'       => 'Sudanese Pound',
                  'entity'         => 'SUDAN (THE)',
                  'minorUnit'      => 2,
                  'numericCode'    => 938,],
        'SRD' => ['alphabeticCode' => 'SRD',
                  'currency'       => 'Surinam Dollar',
                  'entity'         => 'SURINAME',
                  'minorUnit'      => 2,
                  'numericCode'    => 968,],
        'SZL' => ['alphabeticCode' => 'SZL',
                  'currency'       => 'Lilangeni',
                  'entity'         => 'SWAZILAND',
                  'minorUnit'      => 2,
                  'numericCode'    => 748,],
        'SEK' => ['alphabeticCode' => 'SEK',
                  'currency'       => 'Swedish Krona',
                  'entity'         => 'SWEDEN',
                  'minorUnit'      => 2,
                  'numericCode'    => 752,],
        'CHE' => ['alphabeticCode' => 'CHE',
                  'currency'       => 'WIR Euro',
                  'entity'         => 'SWITZERLAND',
                  'minorUnit'      => 2,
                  'numericCode'    => 947,],
        'CHW' => ['alphabeticCode' => 'CHW',
                  'currency'       => 'WIR Franc',
                  'entity'         => 'SWITZERLAND',
                  'minorUnit'      => 2,
                  'numericCode'    => 948,],
        'SYP' => ['alphabeticCode' => 'SYP',
                  'currency'       => 'Syrian Pound',
                  'entity'         => 'SYRIAN ARAB REPUBLIC',
                  'minorUnit'      => 2,
                  'numericCode'    => 760,],
        'TWD' => ['alphabeticCode' => 'TWD',
                  'currency'       => 'New Taiwan Dollar',
                  'entity'         => 'TAIWAN (PROVINCE OF CHINA)',
                  'minorUnit'      => 2,
                  'numericCode'    => 901,],
        'TJS' => ['alphabeticCode' => 'TJS',
                  'currency'       => 'Somoni',
                  'entity'         => 'TAJIKISTAN',
                  'minorUnit'      => 2,
                  'numericCode'    => 972,],
        'TZS' => ['alphabeticCode' => 'TZS',
                  'currency'       => 'Tanzanian Shilling',
                  'entity'         => 'TANZANIA, UNITED REPUBLIC OF',
                  'minorUnit'      => 2,
                  'numericCode'    => 834,],
        'THB' => ['alphabeticCode' => 'THB',
                  'currency'       => 'Baht',
                  'entity'         => 'THAILAND',
                  'minorUnit'      => 2,
                  'numericCode'    => 764,],
        'TOP' => ['alphabeticCode' => 'TOP',
                  'currency'       => 'Pa’anga',
                  'entity'         => 'TONGA',
                  'minorUnit'      => 2,
                  'numericCode'    => 776,],
        'TTD' => ['alphabeticCode' => 'TTD',
                  'currency'       => 'Trinidad and Tobago Dollar',
                  'entity'         => 'TRINIDAD AND TOBAGO',
                  'minorUnit'      => 2,
                  'numericCode'    => 780,],
        'TND' => ['alphabeticCode' => 'TND',
                  'currency'       => 'Tunisian Dinar',
                  'entity'         => 'TUNISIA',
                  'minorUnit'      => 3,
                  'numericCode'    => 788,],
        'TRY' => ['alphabeticCode' => 'TRY',
                  'currency'       => 'Turkish Lira',
                  'entity'         => 'TURKEY',
                  'minorUnit'      => 2,
                  'numericCode'    => 949,],
        'TMT' => ['alphabeticCode' => 'TMT',
                  'currency'       => 'Turkmenistan New Manat',
                  'entity'         => 'TURKMENISTAN',
                  'minorUnit'      => 2,
                  'numericCode'    => 934,],
        'UGX' => ['alphabeticCode' => 'UGX',
                  'currency'       => 'Uganda Shilling',
                  'entity'         => 'UGANDA',
                  'minorUnit'      => 0,
                  'numericCode'    => 800,],
        'UAH' => ['alphabeticCode' => 'UAH',
                  'currency'       => 'Hryvnia',
                  'entity'         => 'UKRAINE',
                  'minorUnit'      => 2,
                  'numericCode'    => 980,],
        'AED' => ['alphabeticCode' => 'AED',
                  'currency'       => 'UAE Dirham',
                  'entity'         => 'UNITED ARAB EMIRATES (THE)',
                  'minorUnit'      => 2,
                  'numericCode'    => 784,],
        'USN' => ['alphabeticCode' => 'USN',
                  'currency'       => 'US Dollar (Next day)',
                  'entity'         => 'UNITED STATES OF AMERICA (THE)',
                  'minorUnit'      => 2,
                  'numericCode'    => 997,],
        'UYU' => ['alphabeticCode' => 'UYU',
                  'currency'       => 'Peso Uruguayo',
                  'entity'         => 'URUGUAY',
                  'minorUnit'      => 2,
                  'numericCode'    => 858,],
        'UYI' => ['alphabeticCode' => 'UYI',
                  'currency'       => 'Uruguay Peso en Unidades Indexadas (URUIURUI)',
                  'entity'         => 'URUGUAY',
                  'minorUnit'      => 0,
                  'numericCode'    => 940,],
        'UZS' => ['alphabeticCode' => 'UZS',
                  'currency'       => 'Uzbekistan Sum',
                  'entity'         => 'UZBEKISTAN',
                  'minorUnit'      => 2,
                  'numericCode'    => 860,],
        'VUV' => ['alphabeticCode' => 'VUV',
                  'currency'       => 'Vatu',
                  'entity'         => 'VANUATU',
                  'minorUnit'      => 0,
                  'numericCode'    => 548,],
        'VEF' => ['alphabeticCode' => 'VEF',
                  'currency'       => 'Bolívar',
                  'entity'         => 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
                  'minorUnit'      => 2,
                  'numericCode'    => 937,],
        'VND' => ['alphabeticCode' => 'VND',
                  'currency'       => 'Đồng',
                  'entity'         => 'VIET NAM',
                  'minorUnit'      => 0,
                  'numericCode'    => 704,],
        'YER' => ['alphabeticCode' => 'YER',
                  'currency'       => 'Yemeni Rial',
                  'entity'         => 'YEMEN',
                  'minorUnit'      => 2,
                  'numericCode'    => 886,],
        'ZMW' => ['alphabeticCode' => 'ZMW',
                  'currency'       => 'Zambian Kwacha',
                  'entity'         => 'ZAMBIA',
                  'minorUnit'      => 2,
                  'numericCode'    => 967,],
        'ZWL' => ['alphabeticCode' => 'ZWL',
                  'currency'       => 'Zimbabwe Dollar',
                  'entity'         => 'ZIMBABWE',
                  'minorUnit'      => 2,
                  'numericCode'    => 932,],
        'XBA' => ['alphabeticCode' => 'XBA',
                  'currency'       => 'Bond Markets Unit European Composite Unit (EURCO)',
                  'entity'         => 'ZZ01_Bond Markets Unit European_EURCO',
                  'minorUnit'      => 0,
                  'numericCode'    => 955,],
        'XBB' => ['alphabeticCode' => 'XBB',
                  'currency'       => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
                  'entity'         => 'ZZ02_Bond Markets Unit European_EMU-6',
                  'minorUnit'      => 0,
                  'numericCode'    => 956,],
        'XBC' => ['alphabeticCode' => 'XBC',
                  'currency'       => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
                  'entity'         => 'ZZ03_Bond Markets Unit European_EUA-9',
                  'minorUnit'      => 0,
                  'numericCode'    => 957,],
        'XBD' => ['alphabeticCode' => 'XBD',
                  'currency'       => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
                  'entity'         => 'ZZ04_Bond Markets Unit European_EUA-17',
                  'minorUnit'      => 0,
                  'numericCode'    => 958,],
        'XTS' => ['alphabeticCode' => 'XTS',
                  'currency'       => 'Codes specifically reserved for testing purposes',
                  'entity'         => 'ZZ06_Testing_Code',
                  'minorUnit'      => 0,
                  'numericCode'    => 963,],
        'XAU' => ['alphabeticCode' => 'XAU',
                  'currency'       => 'Gold',
                  'entity'         => 'ZZ08_Gold',
                  'minorUnit'      => 0,
                  'numericCode'    => 959,],
        'XPD' => ['alphabeticCode' => 'XPD',
                  'currency'       => 'Palladium',
                  'entity'         => 'ZZ09_Palladium',
                  'minorUnit'      => 0,
                  'numericCode'    => 964,],
        'XPT' => ['alphabeticCode' => 'XPT',
                  'currency'       => 'Platinum',
                  'entity'         => 'ZZ10_Platinum',
                  'minorUnit'      => 0,
                  'numericCode'    => 962,],
        'XAG' => ['alphabeticCode' => 'XAG',
                  'currency'       => 'Silver',
                  'entity'         => 'ZZ11_Silver',
                  'minorUnit'      => 0,
                  'numericCode'    => 961,],];