<?php
namespace Craft;

/**
 * The class name is the UTC timestamp in the format of mYYMMDD_HHMMSS_pluginHandle_migrationName
 */
class m150124_100100_stripey_Countries extends BaseMigration
{
	/**
	 * Any migration code in here is wrapped inside of a transaction.
	 *
	 * @return bool
	 */
	public function safeUp()
	{
		$table     = Stripey_CountryRecord::model()->getTableName();
		$countries = array(
			array('AD', 'Andorra'),
			array('AE', 'United Arab Emirates'),
			array('AF', 'Afghanistan'),
			array('AG', 'Antigua and Barbuda'),
			array('AI', 'Anguilla'),
			array('AL', 'Albania'),
			array('AM', 'Armenia'),
			array('AO', 'Angola'),
			array('AQ', 'Antarctica'),
			array('AR', 'Argentina'),
			array('AS', 'American Samoa'),
			array('AT', 'Austria'),
			array('AU', 'Australia'),
			array('AW', 'Aruba'),
			array('AX', 'Aland Islands'),
			array('AZ', 'Azerbaijan'),
			array('BA', 'Bosnia and Herzegovina'),
			array('BB', 'Barbados'),
			array('BD', 'Bangladesh'),
			array('BE', 'Belgium'),
			array('BF', 'Burkina Faso'),
			array('BG', 'Bulgaria'),
			array('BH', 'Bahrain'),
			array('BI', 'Burundi'),
			array('BJ', 'Benin'),
			array('BL', 'Saint Barthelemy'),
			array('BM', 'Bermuda'),
			array('BN', 'Brunei Darussalam'),
			array('BO', 'Bolivia'),
			array('BQ', 'Bonaire, Sint Eustatius and Saba'),
			array('BR', 'Brazil'),
			array('BS', 'Bahamas'),
			array('BT', 'Bhutan'),
			array('BV', 'Bouvet Island'),
			array('BW', 'Botswana'),
			array('BY', 'Belarus'),
			array('BZ', 'Belize'),
			array('CA', 'Canada'),
			array('CC', 'Cocos (Keeling) Islands'),
			array('CD', 'Democratic Republic of Congo'),
			array('CF', 'Central African Republic'),
			array('CG', 'Congo'),
			array('CH', 'Switzerland'),
			array('CI', 'Ivory Coast'),
			array('CK', 'Cook Islands'),
			array('CL', 'Chile'),
			array('CM', 'Cameroon'),
			array('CN', 'China'),
			array('CO', 'Colombia'),
			array('CR', 'Costa Rica'),
			array('CU', 'Cuba'),
			array('CV', 'Cape Verde'),
			array('CW', 'Curacao'),
			array('CX', 'Christmas Island'),
			array('CY', 'Cyprus'),
			array('CZ', 'Czech Republic'),
			array('DE', 'Germany'),
			array('DJ', 'Djibouti'),
			array('DK', 'Denmark'),
			array('DM', 'Dominica'),
			array('DO', 'Dominican Republic'),
			array('DZ', 'Algeria'),
			array('EC', 'Ecuador'),
			array('EE', 'Estonia'),
			array('EG', 'Egypt'),
			array('EH', 'Western Sahara'),
			array('ER', 'Eritrea'),
			array('ES', 'Spain'),
			array('ET', 'Ethiopia'),
			array('FI', 'Finland'),
			array('FJ', 'Fiji'),
			array('FK', 'Falkland Islands (Malvinas)'),
			array('FM', 'Micronesia'),
			array('FO', 'Faroe Islands'),
			array('FR', 'France'),
			array('GA', 'Gabon'),
			array('GB', 'United Kingdom'),
			array('GD', 'Grenada'),
			array('GE', 'Georgia'),
			array('GF', 'French Guiana'),
			array('GG', 'Guernsey'),
			array('GH', 'Ghana'),
			array('GI', 'Gibraltar'),
			array('GL', 'Greenland'),
			array('GM', 'Gambia'),
			array('GN', 'Guinea'),
			array('GP', 'Guadeloupe'),
			array('GQ', 'Equatorial Guinea'),
			array('GR', 'Greece'),
			array('GS', 'S. Georgia and S. Sandwich Isls.'),
			array('GT', 'Guatemala'),
			array('GU', 'Guam'),
			array('GW', 'Guinea-Bissau'),
			array('GY', 'Guyana'),
			array('HK', 'Hong Kong'),
			array('HM', 'Heard and McDonald Islands'),
			array('HN', 'Honduras'),
			array('HR', 'Croatia (Hrvatska)'),
			array('HT', 'Haiti'),
			array('HU', 'Hungary'),
			array('ID', 'Indonesia'),
			array('IE', 'Ireland'),
			array('IL', 'Israel'),
			array('IM', 'Isle Of Man'),
			array('IN', 'India'),
			array('IO', 'British Indian Ocean Territory'),
			array('IQ', 'Iraq'),
			array('IR', 'Iran'),
			array('IS', 'Iceland'),
			array('IT', 'Italy'),
			array('JE', 'Jersey'),
			array('JM', 'Jamaica'),
			array('JO', 'Jordan'),
			array('JP', 'Japan'),
			array('KE', 'Kenya'),
			array('KG', 'Kyrgyzstan'),
			array('KH', 'Cambodia'),
			array('KI', 'Kiribati'),
			array('KM', 'Comoros'),
			array('KN', 'Saint Kitts and Nevis'),
			array('KP', 'Korea (North)'),
			array('KR', 'Korea (South)'),
			array('KW', 'Kuwait'),
			array('KY', 'Cayman Islands'),
			array('KZ', 'Kazakhstan'),
			array('LA', 'Laos'),
			array('LB', 'Lebanon'),
			array('LC', 'Saint Lucia'),
			array('LI', 'Liechtenstein'),
			array('LK', 'Sri Lanka'),
			array('LR', 'Liberia'),
			array('LS', 'Lesotho'),
			array('LT', 'Lithuania'),
			array('LU', 'Luxembourg'),
			array('LV', 'Latvia'),
			array('LY', 'Libya'),
			array('MA', 'Morocco'),
			array('MC', 'Monaco'),
			array('MD', 'Moldova'),
			array('ME', 'Montenegro'),
			array('MF', 'Saint Martin (French part)'),
			array('MG', 'Madagascar'),
			array('MH', 'Marshall Islands'),
			array('MK', 'Macedonia'),
			array('ML', 'Mali'),
			array('MM', 'Burma (Myanmar)'),
			array('MN', 'Mongolia'),
			array('MO', 'Macau'),
			array('MP', 'Northern Mariana Islands'),
			array('MQ', 'Martinique'),
			array('MR', 'Mauritania'),
			array('MS', 'Montserrat'),
			array('MT', 'Malta'),
			array('MU', 'Mauritius'),
			array('MV', 'Maldives'),
			array('MW', 'Malawi'),
			array('MX', 'Mexico'),
			array('MY', 'Malaysia'),
			array('MZ', 'Mozambique'),
			array('NA', 'Namibia'),
			array('NC', 'New Caledonia'),
			array('NE', 'Niger'),
			array('NF', 'Norfolk Island'),
			array('NG', 'Nigeria'),
			array('NI', 'Nicaragua'),
			array('NL', 'Netherlands'),
			array('NO', 'Norway'),
			array('NP', 'Nepal'),
			array('NR', 'Nauru'),
			array('NU', 'Niue'),
			array('NZ', 'New Zealand'),
			array('OM', 'Oman'),
			array('PA', 'Panama'),
			array('PE', 'Peru'),
			array('PF', 'French Polynesia'),
			array('PG', 'Papua New Guinea'),
			array('PH', 'Philippines'),
			array('PK', 'Pakistan'),
			array('PL', 'Poland'),
			array('PM', 'St. Pierre and Miquelon'),
			array('PN', 'Pitcairn'),
			array('PR', 'Puerto Rico'),
			array('PS', 'Palestinian Territory, Occupied'),
			array('PT', 'Portugal'),
			array('PW', 'Palau'),
			array('PY', 'Paraguay'),
			array('QA', 'Qatar'),
			array('RE', 'Reunion'),
			array('RO', 'Romania'),
			array('RS', 'Republic of Serbia'),
			array('RU', 'Russia'),
			array('RW', 'Rwanda'),
			array('SA', 'Saudi Arabia'),
			array('SB', 'Solomon Islands'),
			array('SC', 'Seychelles'),
			array('SD', 'Sudan'),
			array('SE', 'Sweden'),
			array('SG', 'Singapore'),
			array('SH', 'St. Helena'),
			array('SI', 'Slovenia'),
			array('SJ', 'Svalbard and Jan Mayen Islands'),
			array('SK', 'Slovak Republic'),
			array('SL', 'Sierra Leone'),
			array('SM', 'San Marino'),
			array('SN', 'Senegal'),
			array('SO', 'Somalia'),
			array('SR', 'Suriname'),
			array('SS', 'South Sudan'),
			array('ST', 'Sao Tome and Principe'),
			array('SV', 'El Salvador'),
			array('SX', 'Sint Maarten (Dutch part)'),
			array('SY', 'Syria'),
			array('SZ', 'Swaziland'),
			array('TC', 'Turks and Caicos Islands'),
			array('TD', 'Chad'),
			array('TF', 'French Southern Territories'),
			array('TG', 'Togo'),
			array('TH', 'Thailand'),
			array('TJ', 'Tajikistan'),
			array('TK', 'Tokelau'),
			array('TL', 'Timor-Leste'),
			array('TM', 'Turkmenistan'),
			array('TN', 'Tunisia'),
			array('TO', 'Tonga'),
			array('TR', 'Turkey'),
			array('TT', 'Trinidad and Tobago'),
			array('TV', 'Tuvalu'),
			array('TW', 'Taiwan'),
			array('TZ', 'Tanzania'),
			array('UA', 'Ukraine'),
			array('UG', 'Uganda'),
			array('UM', 'United States Minor Outlying Islands'),
			array('US', 'United States'),
			array('UY', 'Uruguay'),
			array('UZ', 'Uzbekistan'),
			array('VA', 'Vatican City State (Holy See)'),
			array('VC', 'Saint Vincent and the Grenadines'),
			array('VE', 'Venezuela'),
			array('VG', 'Virgin Islands (British)'),
			array('VI', 'Virgin Islands (U.S.)'),
			array('VN', 'Viet Nam'),
			array('VU', 'Vanuatu'),
			array('WF', 'Wallis and Futuna Islands'),
			array('WS', 'Samoa'),
			array('YE', 'Yemen'),
			array('YT', 'Mayotte'),
			array('ZA', 'South Africa'),
			array('ZM', 'Zambia'),
			array('ZW', 'Zimbabwe'),
		);

		craft()->db->createCommand()->insertAll($table, array('iso', 'name'), $countries);

		return true;
	}
}
