name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - '5.0'
  pull_request:
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: ci
    uses: craftcms/.github/.github/workflows/ci.yml@v3
    with:
      craft_version: '5'
      jobs: '["ecs", "phpstan", "prettier", "tests"]'
      notify_slack: true
      slack_subteam: <!subteam^S01CWPYH9D5>
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_COMMERCE_WEBHOOK_URL }}
